class GameState:
    MENU = "menu"
    GAME = "game"
    SHOP = "shop"
    SETTINGS = "settings"
    DIFF = "diff"
    SAVES = "saves"
    HOWTO = "howto"
    UPGRADES = "upgrades"
    GAME_OVER = "game_over"
    WIN = "win"
